import './globals.css';
import { Inter } from 'next/font/google';
import { clientEnv } from '@/constants';
import AppProvider from '@/providers/app';

const intr = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Create Next App',
    template: `%s | Next App`,
  },
  description: 'Generated by create next app',
  // https://zenn.dev/temasaguru/articles/641a10cd5af02a
  metadataBase: new URL(clientEnv.NEXT_PUBLIC_HOST_URL),
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={intr.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
